name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: IRC notification
        uses: Gottox/irc-message-action@v1
        with:
          channel: '#repla-development'
          nickname: ${{ github.run_id }}-bot
          message: |-
            ${{ github.event.repository.name }} ${{ github.action }} started ${{ github.actor }} pushed ${{ github.event.ref }} ${{ github.event.compare }}
      - run: make ci
      - name: IRC notification
        uses: Gottox/irc-message-action@v1
        with:
          channel: '#repla-development'
          nickname: ${{ github.run_id }}-bot
          message: |-
            ${{ github.event.repository.name }} ${{ github.action }} finished ${{ github.actor }} pushed ${{ github.event.ref }} ${{ github.event.compare }}
